name: pickup
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_signin_button: ^2.0.0
  weekly_date_picker: ^1.4.2
  flutter_form_builder: ^9.2.1
  form_builder_image_picker: ^4.0.0
  form_builder_validators: ^9.1.0
  # firebase_in_app_messaging: ^0.7.4+17
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  logger: ^2.1.0
  cloud_firestore: ^4.15.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
